"""
Django settings for parul_library project.
Parul University - Library Management System

Generated by 'django-admin startproject' using Django 5.0.4.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vbnus643(kmarn6#&onddsv(r!@0cqt@gn1d^9git8docq3we='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ============================================================
# Application definition
# 'library_app' is our custom app for the Library system
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',       # Django admin panel
    'django.contrib.auth',        # Authentication system (login/logout)
    'django.contrib.contenttypes',
    'django.contrib.sessions',    # Session management
    'django.contrib.messages',    # Flash messages
    'django.contrib.staticfiles', # Static files (CSS, JS, images)
    'library_app',                # Our Library Management app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parul_library.urls'

# ============================================================
# Template configuration
# We tell Django to look inside 'templates/' folder at project root
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Project-level templates folder
        'APP_DIRS': True,                   # Also look in app-level templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parul_library.wsgi.application'


# ============================================================
# Database - Using SQLite (default, no extra setup needed)
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================================================
# Internationalization - Set to Indian Standard Time
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # IST for Parul University, Gujarat

USE_I18N = True

USE_TZ = True


# ============================================================
# Static files (CSS, JavaScript, Images)
# ============================================================

# ============================================================
# Static & Media files (CSS, JavaScript, Images)
# ============================================================

STATIC_URL = 'static/'

# Media files (Uploaded photos, documents)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# Authentication Redirects
# These tell Django where to go after login/logout
# ============================================================

LOGIN_URL = 'login'               # Name of the login URL (redirects here if not logged in)
LOGIN_REDIRECT_URL = 'dashboard'  # After successful login, go to dashboard
LOGOUT_REDIRECT_URL = 'login'     # After logout, go back to login page
