# Generated by Django 5.0.4 on 2026-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the book title', max_length=200)),
                ('author', models.CharField(help_text='Enter the author name', max_length=200)),
                ('isbn', models.CharField(help_text='Enter 13-digit ISBN number', max_length=13, unique=True, verbose_name='ISBN')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of copies available')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the student's full name", max_length=200)),
                ('enrollment_no', models.CharField(help_text='Enter unique enrollment number', max_length=20, unique=True, verbose_name='Enrollment No.')),
                ('email', models.EmailField(help_text="Enter the student's email address", max_length=254)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
    ]
