# Generated by Django 5.0.4 on 2026-05-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True, help_text='Date of issue (auto-filled)')),
                ('due_date', models.DateField(help_text='Date by which book must be returned')),
                ('return_date', models.DateField(blank=True, help_text='Date when book was returned (empty if not returned)', null=True)),
                ('book', models.ForeignKey(help_text='Select the book', on_delete=django.db.models.deletion.CASCADE, related_name='issue_records', to='library_app.book')),
                ('student', models.ForeignKey(help_text='Select the student', on_delete=django.db.models.deletion.CASCADE, related_name='issued_books', to='library_app.student')),
            ],
            options={
                'verbose_name': 'Issue Record',
                'verbose_name_plural': 'Issue Records',
                'ordering': ['-issue_date'],
            },
        ),
    ]
