# Generated by Django 5.0.4 on 2026-05-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_issuerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload student photo', null=True, upload_to='students/'),
        ),
    ]
